---
title: "Faqs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here you can find a list of Frequently Asked Questions on AquaPlan. Please consult these questions initially in the event of issues or queries regarding AquaPlan and its simulation outputs. 

**Q: What data does AquaPlan use as inputs for simulations?**\
Data used to run AquaPlan come from a range of regional and global open-source products. If the selected region is inside the United States, weather data is sourced from Daymet. For any other region, weather data is sourced from NASA-POWER. Soil hydaulic properties are derived from the SoilGrids dataset, or from default soil classes provided as part of the AquaCrop. Crop growth parameters for a range of crops are also obtained from the default parameter settings included in the AquaCrop model. The latter can be customised, including to create new crop types, using the 'Customise Crop Parameters' tool provided with AquaPlan.\
\

**Q: I am not able to access the Run AquaCrop menu when I select a location by speciyfing coordinates in the search box - how do I solve this issue?**\
This is caused by an issue with the way that Streamlit stores the point location generated by the interactive map. As a temporary fix, you will need to select the intended location manually by zooming in and placing a marker in the same location. We are working on a long-term fix to this issue and will remove this question from the faq when this issue is solved.\
\

**Q: Why does the app show as 'Running' when first initiated?**\
Several of the underlying AquaCrop model functions are compiled ahead of time (AOT) in order to improve performance and reduce run time, especially when executing via the AquaPlan web application. Once compilation has occurred, this process will not need to be repeated and you won't need to wait again unless you relaunch the app in a new session or browser.\

Very occasionally, AquaPlan will fail to compile the underlying AquaCrop code (indicated by an error saying certain modules could not be found). This is due to a currently unexplained issue with Numba AOT compilation on Streamlit Cloud. In the event you encounter this issue, please contact the AquaPlan developers via the details given in the 'Feedback and Contact Info' section of the app. We are currently working on a long-term fix for this issue. \
\
**Q: Why did my simulation not execute when I hit 'Run Model'?**\
Sometimes AquaPlan will currently fail to execute when you hit 'Run Model' for the first time, due to a quirk in the way Streamlit caches changes in input parameters or variables selected through the interactive menus. In this case, you will need to hit 'Run Model' a second time to properly execute the model and ensure outputs are updated.\
\
**Q: I received an error message saying 'Oh no' when running the app - what should I do to fix this?**\
The most common cause of this error is if the app reaches the memory limits provided by Streamlit Cloud when being run online. This usually occurs if using a resource intensive part of the app - specifically the CMIP6 data downloader - or if large number of users are using the app simultaneously. For these reasons, we DO NOT currently advise you to run the CMIP6 data downloader online and only to use this tool locally. \

If you encounter this error, please email the AquaPlan developers via the details given in the 'Feedback and Contact Info' section of the app, and they will be able to reset the app (note this will affect all active users). You can also install the AquaPlan app on your local machine where you will likely have greater memory available, instructions for which are given in the 'Get Started' section of this website.\
\
**Q: Why did my session unexpectedly restart?**\
It is occasionally necessary for us to reboot the AquaPlan app in the event of a major code failure or change. In this case, all active user sessions will be affected and wil restart automatically. This process should only take a few minutes from start to completion, and will only affect instances of the app running on Streamlit Cloud - local installations will not be affected. \
\